// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/nanfeng/ginchat/internal/config"
	"github.com/nanfeng/ginchat/internal/handler/v1"
	"github.com/nanfeng/ginchat/internal/repository"
	"github.com/nanfeng/ginchat/internal/server"
	"github.com/nanfeng/ginchat/internal/service"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
	"log"
	"net/http"
	"os"
	"time"
)

// Injectors from wire.go:

func BuildApp() (*App, error) {
	appConfig := config.Init()
	db, err := NewDB(appConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := v1.NewUserHandler(userService)
	httpServer := server.NewHTTPServer(userHandler)
	app := &App{
		DB:         db,
		HTTPServer: httpServer,
	}
	return app, nil
}

// wire.go:

type App struct {
	DB *gorm.DB
	// 可以后续加其他字段，例如：
	// Config    *config.AppConfig
	// Logger    *zap.Logger
	HTTPServer *http.Server
}

func NewDB(cfg *config.AppConfig) (*gorm.DB, error) {
	newLogger := logger.New(log.New(os.Stdout, "\r\n", log.LstdFlags), logger.Config{
		SlowThreshold: time.Second,
		LogLevel:      logger.Info,
		Colorful:      true,
	},
	)

	db, err := gorm.Open(mysql.Open(cfg.Database.Dsn), &gorm.Config{
		Logger: newLogger,
	})

	if err != nil {
		return nil, err
	}

	return db, nil
}
